---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: centos-6.4
    run_list:
      - recipe[yum-epel]
  - name: sles-11sp3
    driver_config:
      box: opscode-sles-11sp3
    run_list:
      - recipe[zypper]
    attributes: {
      java: {
        install_flavor: 'oracle',
        oracle: {
          accept_oracle_download_terms: true
          }
        }
      }

suites:
  - name: default
    run_list:
      - recipe[logstash]
    attributes: {}
  - name: lwrp
    run_list:
      - recipe[logstash_test]
    attributes: {}
  - name: bluepill
    run_list:
      - recipe[logstash_test]
    attributes: {
      logstash: {
        service_provider: 'bluepill'
        }
      }
