---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: centos-6.4
    run_list:
      - recipe[yum-epel]

suites:
  - name: default
    run_list:
      - recipe[logstash]
    attributes:
  - name: lwrp
    run_list:
      - recipe[logstash_test]
  - name: agent
    run_list:
      - recipe[logstash::agent]
    attributes:
  - name: server
    run_list:
      - recipe[logstash::server]
    attributes:
