name             'logstash'
maintainer       'Texas A&M'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures lib-logstash'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.2'
depends          'bluepill'
depends          'apache2'
depends          'java'
depends          'elasticsearch'
